# **Matrix Multiplication **
## We will use tf.mantmul() method

1. Inner dimension must match --> (m,n)@(n,p). e.g:-
* (5,7)@(8,9) It will not work because innerdimension is different
* (5,7)@(7,9) It will work because inner dimension is the same




2. The result matrix has the shape of outer dimension. e.g:-
* A(m,n)B(n,p) = (m,p)
* (4,7)@(7,5) = (4,5)




In [2]:
import tensorflow as tf
import numpy as np

In [7]:
tensor_a = tf.constant([[1,2],[3,4],[4,5]],dtype=tf.int32)
tensor_b = tf.constant([[5,6],[7,8]],dtype=tf.int32)
print("Shape of A",tensor_a.shape)
print("Shape of B",tensor_b.shape)

Shape of A (3, 2)
Shape of B (2, 2)


In [10]:
tensor_c = tf.matmul(tensor_a,tensor_b)
print(tensor_c)
print("Shape of C",tensor_c.shape)

tf.Tensor(
[[19 22]
 [43 50]
 [55 64]], shape=(3, 2), dtype=int32)
Shape of C (3, 2)


In [12]:
X = tf.constant([[1.,0.,-1.],
                 [2.,3.,1.]]
                 ,dtype=tf.float32)
X

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  0., -1.],
       [ 2.,  3.,  1.]], dtype=float32)>

In [13]:
Y = tf.constant([[4.],
                 [5.],
                 [6.]
                 ],dtype=tf.float32)
Y

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[4.],
       [5.],
       [6.]], dtype=float32)>

In [14]:
print("X-Shape",X.shape)
print("Y-Shape",Y.shape)

X-Shape (2, 3)
Y-Shape (3, 1)


In [15]:
z=tf.matmul(X,Y)
z

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-2.],
       [29.]], dtype=float32)>

In [17]:
print(f"X-shape: {X.shape},Y-shape: {Y.shape}, z-shape: {z.shape}")
print(X.numpy())
print(Y.numpy())
print(z.numpy())

X-shape: (2, 3),Y-shape: (3, 1), z-shape: (2, 1)
[[ 1.  0. -1.]
 [ 2.  3.  1.]]
[[4.]
 [5.]
 [6.]]
[[-2.]
 [29.]]


Transpose : Transpose swaps axes. For 2D matrix shape(m,n) become (n,m) after transpose

In [20]:
tensor_one=tf.constant([
    [[1,2],[2,3]],
    [[4,5],[6,7]],], dtype=tf.int32)
tensor_one
print("Shape of tension_one: ",tensor_one.shape)

Shape of tension_one:  (2, 2, 2)


In [23]:
tensor_one_transpose=tf.transpose(tensor_one)
print(tensor_one_transpose)
print("Shape of tension_one_transpose: ",tensor_one_transpose.shape)


tf.Tensor(
[[[1 4]
  [2 6]]

 [[2 5]
  [3 7]]], shape=(2, 2, 2), dtype=int32)
Shape of tension_one_transpose:  (2, 2, 2)


In [25]:
# 3D Tranpose with explicit axis permutation
tensor_two = tf.constant([
    [[1,2],[3,4]],
    [[5,6],[7,8]]], dtype=tf.int32)
print(tensor_two)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [26]:
# swap first and last axis (0,1,2)->(0,2,1)
t2_transpose = tf.transpose(tensor_two,perm=[0,2,1])
print(t2_transpose)
print("Shape of t2_transpose",t2_transpose.shape)
print("Shape of tensor_two",tensor_two.shape)

tf.Tensor(
[[[1 3]
  [2 4]]

 [[5 7]
  [6 8]]], shape=(2, 2, 2), dtype=int32)
Shape of t2_transpose (2, 2, 2)
Shape of tensor_two (2, 2, 2)


**Reshape**
# tf.reshape(tensor,new_shape)
# Change the shape without changing the data
**Rule** : The total number of element must stay the same


In [29]:
tensor=tf.constant(
    [[1,2,3],
    [4,5,6]], dtype=tf.int32
)
print(tensor)
print("Shape of tensor",tensor.shape)
print("Number of element are: ",tf.size(tensor).numpy())

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Shape of tensor (2, 3)
Number of element are:  6


In [30]:
tensor_r1=tf.reshape(tensor,shape=(3,2))
print(tensor_r1)
print("Shape of tensor_r1",tensor_r1.shape)
print("Number of element are: ",tf.size(tensor_r1).numpy())

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Shape of tensor_r1 (3, 2)
Number of element are:  6


In [31]:
tensor_r2=tf.reshape(tensor,shape=(6,1))
print(tensor_r2)
print("Shape of tensor_r1",tensor_r2.shape)
print("Number of element are: ",tf.size(tensor_r2).numpy())

tf.Tensor(
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]], shape=(6, 1), dtype=int32)
Shape of tensor_r1 (6, 1)
Number of element are:  6


In [32]:
tensor_r3=tf.reshape(tensor,shape=(1,6))
print(tensor_r3)
print("Shape of tensor_r1",tensor_r3.shape)
print("Number of element are: ",tf.size(tensor_r3).numpy())

tf.Tensor([[1 2 3 4 5 6]], shape=(1, 6), dtype=int32)
Shape of tensor_r1 (1, 6)
Number of element are:  6


In [33]:
# infer dimension- if put -1 it will be decide the appropriate number to get total 6 element
tensor_r4=tf.reshape(tensor,shape=(-1,2))
print(tensor_r4)
print("Shape of tensor_r1",tensor_r4.shape)
print("Number of element are: ",tf.size(tensor_r4).numpy())

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Shape of tensor_r1 (3, 2)
Number of element are:  6


In [34]:
tensor_r5=tf.reshape(tensor,shape=(-1,3))
print(tensor_r5)
print("Shape of tensor_r1",tensor_r5.shape)
print("Number of element are: ",tf.size(tensor_r5).numpy())

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Shape of tensor_r1 (2, 3)
Number of element are:  6


In [35]:
# To do : Reshape (2,6) -> (3,4) and (1,12)
tensor_given = tf.constant([
    [1,2,3,4,5,6],
    [7,8,9,10,11,12]
],dtype=tf.int32)
print(tensor_given)

tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]], shape=(2, 6), dtype=int32)


In [43]:
tensor_given = tf.reshape(tensor_given,shape=(3,4))
print(tensor_given)
print("Shape of tensor_given",tensor_given.shape)
print("Number of element are: ",tf.size(tensor_given).numpy())

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)
Shape of tensor_given (3, 4)
Number of element are:  12


In [44]:
tensor_given = tf.reshape(tensor_given,shape=(1,12))
print(tensor_given)
print("Shape of tensor_given",tensor_given.shape)
print("Number of element are: ",tf.size(tensor_given).numpy())

tf.Tensor([[ 1  2  3  4  5  6  7  8  9 10 11 12]], shape=(1, 12), dtype=int32)
Shape of tensor_given (1, 12)
Number of element are:  12
