# We are going to start TensorFlow Basic 😲

In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.19.0


In [4]:
# creating Tensor with constant
# Function here that we can use to create
scalar=tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [5]:
scalar.ndim # ndim --> dimension

0

In [6]:
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
matrix=tf.constant([[5,9],[9,11]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  9],
       [ 9, 11]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
second_matrix=tf.constant([[5,7],
                           [3,8],
                           [3,9],
                           [4,2],
                           [8,6]])

In [11]:
second_matrix

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[5, 7],
       [3, 8],
       [3, 9],
       [4, 2],
       [8, 6]], dtype=int32)>

In [12]:
second_matrix.ndim

2

In [13]:
third_matrix=tf.constant([[
                          [1,2,3],
                          [2,4,5]],
                          [[7,9,3],
                          [10,4,5]],
                          [[11,2,3],
                          [2,4,15]]
                          ])
third_matrix

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  4,  5]],

       [[ 7,  9,  3],
        [10,  4,  5]],

       [[11,  2,  3],
        [ 2,  4, 15]]], dtype=int32)>

In [14]:
third_matrix.ndim

3

In [15]:
second_matrix=tf.constant([[5.6,7.3],
                           [3.45,8.25],
                           [3.11,9.23],
                           [4.34,2.34],
                           [8.4,6.23]], dtype=tf.float32)
print(second_matrix)

tf.Tensor(
[[5.6  7.3 ]
 [3.45 8.25]
 [3.11 9.23]
 [4.34 2.34]
 [8.4  6.23]], shape=(5, 2), dtype=float32)


In [16]:
# single Number that means scalar
scalar=tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [17]:
# A number with direction
vector=tf.constant([10,10,20,30])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 10, 20, 30], dtype=int32)>

In [18]:
# A 2-D array of numbers
matrix=tf.constant([[10,20],[30,40]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [19]:
# Tensor : an n-dimensional array of numbers(n=0,n=1,n=2.....)
tensor=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [20]:
# Find the shape,dimension,rank and size of tensors
print("Scalar Information")
print("Shape:", scalar.shape)
print("Dimension:", scalar.ndim)
print("Rank:", tf.rank(scalar).numpy())
print("Size:", tf.size(scalar))


Scalar Information
Shape: ()
Dimension: 0
Rank: 0
Size: tf.Tensor(1, shape=(), dtype=int32)


In [21]:
# Find the vector shape,dimension,rank and size
print("Vector Information")
print("Shape:", vector.shape)
print("Dimension:", vector.ndim)
print("Rank:", tf.rank(vector).numpy())
print("Size:", tf.size(vector))

Vector Information
Shape: (4,)
Dimension: 1
Rank: 1
Size: tf.Tensor(4, shape=(), dtype=int32)


In [22]:
# Find the Matrix shape,dimension,rank and size
print("Matrix Information")
print("Shape:", matrix.shape)
print("Dimension:", matrix.ndim)
print("Rank:", tf.rank(matrix).numpy())
print("Size:", tf.size(matrix))

Matrix Information
Shape: (2, 2)
Dimension: 2
Rank: 2
Size: tf.Tensor(4, shape=(), dtype=int32)


In [23]:
# Find the Tensor shape,dimension,rank and size
print("Tensor Information")
print("Shape:", tensor.shape)
print("Dimension:", tensor.ndim)
print("Rank:", tf.rank(tensor).numpy())
print("Size:", tf.size(tensor))

Tensor Information
Shape: (2, 2, 2)
Dimension: 3
Rank: 3
Size: tf.Tensor(8, shape=(), dtype=int32)


In [24]:
#Creating Tensor using Variables
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [25]:
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [26]:
changeable_tensor[1].assign(15)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 15], dtype=int32)>

In [27]:
#unchangeable_tensor[0].assign(12)
#unchangeable_tensor
# will got error because it is unchangeable.you can't change constant tensor, they are immutable i.e unchangeable.

In [28]:
# Random Tensors
random_tensor=tf.random.Generator.from_seed(42)
random_tensor=random_tensor.normal(shape=(3,2))
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [29]:
random_tensor_2=tf.random.uniform(shape=(300,150),minval=0,maxval=1)
random_tensor_2

<tf.Tensor: shape=(300, 150), dtype=float32, numpy=
array([[0.6549349 , 0.6917665 , 0.767918  , ..., 0.94239366, 0.81508553,
        0.5950198 ],
       [0.11603951, 0.762488  , 0.32247937, ..., 0.68483734, 0.48688483,
        0.6191312 ],
       [0.34362864, 0.06802094, 0.79505575, ..., 0.9806334 , 0.9520184 ,
        0.60862267],
       ...,
       [0.32512856, 0.98163366, 0.6552348 , ..., 0.14941669, 0.31860435,
        0.35997438],
       [0.5165323 , 0.90987957, 0.65329623, ..., 0.00372231, 0.2393713 ,
        0.44803703],
       [0.33903205, 0.69698644, 0.47808266, ..., 0.06503963, 0.10441077,
        0.906338  ]], dtype=float32)>

In [30]:
# same seed same values
random_tensor_3=tf.random.Generator.from_seed(42)
random_tensor_3=random_tensor_3.normal(shape=(3,2))
random_tensor_4=tf.random.Generator.from_seed(42)
random_tensor_4=random_tensor_4.normal(shape=(3,2))
random_tensor_3,random_tensor_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [31]:
#Differentseed different tesnors
random_tensor_3=tf.random.Generator.from_seed(42)
random_tensor_3=random_tensor_3.normal(shape=(3,2))
random_tensor_4=tf.random.Generator.from_seed(15)
random_tensor_4=random_tensor_4.normal(shape=(3,2))
random_tensor_3,random_tensor_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.33149973, -0.5445254 ],
        [ 1.5222508 ,  0.59303206],
        [-0.63509274,  0.3703566 ]], dtype=float32)>)

In [32]:
# creating tensors usinh zeros
tensors_zero=tf.zeros(shape=(3,4),dtype=tf.dtypes.int16)
tensors_zero

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

In [33]:
tensors_zero=tf.zeros(shape=(3,4),dtype=tf.dtypes.float32)
tensors_zero

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [34]:
#Tensors for all ones
tensors_ones=tf.ones(shape=(3,4),dtype=tf.dtypes.int16)
tensors_ones

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)>

In [35]:
import numpy as np
numpy_Array=np.arange(1,25,dtype=np.int16)
numpy_Array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [36]:
tensor_numpy=tf.constant(numpy_Array,shape=(2,3,4))
tensor_numpy

<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int16)>

In [37]:
print("Tensor Information")
print("Shape:", tensor_numpy.shape)
print("Dimension:", tensor_numpy.ndim)
print("Rank:", tf.rank(tensor_numpy).numpy())
print("Size:", tf.size(tensor_numpy))
print("DataType of elements: ",tensor_numpy.dtype)
print("Element along axis 0 :",tensor_numpy.shape[0])
print("Element along axis 1 :",tensor_numpy.shape[1])
print("Element along axis 2 :",tensor_numpy.shape[2])
print("Total number of element: ", tf.size(tensor_numpy).numpy())

Tensor Information
Shape: (2, 3, 4)
Dimension: 3
Rank: 3
Size: tf.Tensor(24, shape=(), dtype=int32)
DataType of elements:  <dtype: 'int16'>
Element along axis 0 : 2
Element along axis 1 : 3
Element along axis 2 : 4
Total number of element:  24


In [38]:
# Working with items of each dimension
tensor_numpy[:3,:3,:3]

<tf.Tensor: shape=(2, 3, 3), dtype=int16, numpy=
array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]],

       [[13, 14, 15],
        [17, 18, 19],
        [21, 22, 23]]], dtype=int16)>

In [39]:
# First two elements of each dimension
tensor_numpy[:2,:2,:2] # dua array : dua row : dua column

<tf.Tensor: shape=(2, 2, 2), dtype=int16, numpy=
array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]], dtype=int16)>

**Arithmetic Operation with Tensor**
*   Add
*   Sub
*   Multi
*   Div





In [40]:
tensor_one=tf.constant([[11,9],[2,5]])
tensor_one

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  9],
       [ 2,  5]], dtype=int32)>

In [41]:
# tensor_one+15 #one way
tf.add(tensor_one,15) #second way

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 24],
       [17, 20]], dtype=int32)>

In [42]:
# tensor_one-5 #one way
tf.subtract(tensor_one,5) #second way

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  4],
       [-3,  0]], dtype=int32)>

In [43]:
# tensor_one*3 #one way
tf.multiply(tensor_one,3) #second way

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[33, 27],
       [ 6, 15]], dtype=int32)>

In [44]:
# tensor_one/2 # one way
tf.divide(tensor_one,2) #second way

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5.5, 4.5],
       [1. , 2.5]])>

In [45]:
tensor_new=tf.square(tensor_one)
tensor_new

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  81],
       [  4,  25]], dtype=int32)>

In [46]:
second_matrix=tf.constant([[8,16],
                           [64,8.25],
                           [625,9.23],
                           [125,2.34],
                           [169,144]],dtype=tf.float32)
second_matrix

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[  8.  ,  16.  ],
       [ 64.  ,   8.25],
       [625.  ,   9.23],
       [125.  ,   2.34],
       [169.  , 144.  ]], dtype=float32)>

In [47]:
tf.sqrt(second_matrix)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 2.828427 ,  4.       ],
       [ 8.       ,  2.8722813],
       [25.       ,  3.0380914],
       [11.18034  ,  1.5297059],
       [13.       , 12.       ]], dtype=float32)>

**Exercise**
1. Create two tensors with random value between 0 and 1, shape is [6,300]
2. Found out the follow details : Number of element, size, rank & Shape

In [51]:
# Create two tensors with random value between 0 and 1, shape is [6,300]
random2_tensor=tf.random.uniform(shape=(6,300),minval=0,maxval=1)
random2_tensor

<tf.Tensor: shape=(6, 300), dtype=float32, numpy=
array([[0.07408011, 0.28308666, 0.66621447, ..., 0.8622738 , 0.21640539,
        0.21799743],
       [0.6197891 , 0.80386484, 0.72495663, ..., 0.65649784, 0.468014  ,
        0.22259986],
       [0.3614993 , 0.25265098, 0.6633897 , ..., 0.20832789, 0.09130168,
        0.6473131 ],
       [0.72137606, 0.5852206 , 0.3385589 , ..., 0.1451844 , 0.17414212,
        0.4355495 ],
       [0.89612854, 0.80724216, 0.71490014, ..., 0.47486985, 0.02484393,
        0.26845658],
       [0.5621606 , 0.32648075, 0.5988512 , ..., 0.5766696 , 0.5113921 ,
        0.75223815]], dtype=float32)>

In [52]:
# Found out the follow details : Number of element, size, rank & Shape
print("Random2_tensor Information")
print("Total number of element: ", tf.size(random2_tensor).numpy())
print("Size:", tf.size(random2_tensor))
print("Rank:", tf.rank(random2_tensor).numpy())
print("Shape:", random2_tensor.shape)
print("Dimension:", random2_tensor.ndim)

Random2_tensor Information
Total number of element:  1800
Size: tf.Tensor(1800, shape=(), dtype=int32)
Rank: 2
Shape: (6, 300)
Dimension: 2
