# Numpy Introduction and usage
## We will use numpy in this jupyter notebook

# One Dimensional Array (1-d)

In [102]:

import numpy as np

In [3]:
array1=np.array([10,20,30,40,50])

In [4]:
print(array1)

[10 20 30 40 50]


# Two Dimensional Array (2-D)

In [6]:
array_two=np.array([[10,20,30],[40,50,60]])

In [7]:
print(array_two)

[[10 20 30]
 [40 50 60]]


# Three Dimensional Array (3-D Array)

In [11]:
array_three=np.array([[[10,20,30],[40,50,60]],[[80,40,90],[40,30,20]]])

In [12]:
print(array_three)

[[[10 20 30]
  [40 50 60]]

 [[80 40 90]
  [40 30 20]]]


# Find out Dimension of Numpy array

In [13]:
print('First Array Dimension: ',array1.ndim)

First Array Dimension:  1


In [14]:
print('Second Array Dimension: ',array_two.ndim)

Second Array Dimension:  2


In [15]:
print('Three Array Dimension: ',array_three.ndim)

Three Array Dimension:  3


# Write an array of 5 students marks using Numpy
    ##Marks are: 80,70,99,89

In [16]:
array_marks=np.array([80,70,99,89])

In [25]:
print('Array of student marks')
print(array_marks)

Array of student marks
[80 70 99 89]


# Write an array:to take Marks of 5 students in 3 subjects using Numpy
## Math,English,Chemistry
## [[50,45,49],[40,42,45],[35,40,46],[39,40,50],[49,40,50]]

In [26]:
array_marks_sub=np.array([[50,45,49],[40,42,45],[35,40,46],[39,40,50],[49,40,50]])
print('2-D Array Example')
print(array_marks_sub)

2-D Array Example
[[50 45 49]
 [40 42 45]
 [35 40 46]
 [39 40 50]
 [49 40 50]]


# Write an array: to take Marks of 4 students in 3 subject for two semseter using Numpy
    ## Student Name are: 'Dila','Syasa','Mira','Arif','Chun Wei'
    ## Math, English, Chemistry
    ## Two semester : sem1 , sem2
    ## 4*3*2
    ## [[[85,89],[78,90],[88,90]],[[90,85],[96,79],[93,88]],[[75,85],[77,80],[80,88]],[[67,80],[72,79],[77,87]]]


In [29]:
marks_subject_sem=np.array([[[85,89],[78,90],[88,90]],
                            [[90,85],[96,79],[93,88]],
                            [[75,85],[77,80],[80,88]],
                            [[67,80],[72,79],[77,87]]])

In [30]:
print(marks_subject_sem)

[[[85 89]
  [78 90]
  [88 90]]

 [[90 85]
  [96 79]
  [93 88]]

 [[75 85]
  [77 80]
  [80 88]]

 [[67 80]
  [72 79]
  [77 87]]]


## Write an array: to take Wheater of 2 cities in 3 days for three times in a day morning,noon and evening¶
    ## cities Names area: 'Kuala Lumpur', 'Delhi'
    ## Saturday, Sunday ,Monday
    ## Three time slot: Morning, Noon and Evening
## Create one 3-D Array for this using NumPy and print it


In [36]:
City_Wheater=np.array([[['cloudy','raining','raining'],['Partly Cloudy','Sunny','Partly Cloudy'],['Sunny','Sunny','Partly Cloudy']],
                      [['sunny','sunny','Partly sunny'],['Raining','Sunny','Partly Cloudy'],['Sunny','windy','Partly Cloudy']]])
print(City_Wheater)
                      

[[['cloudy' 'raining' 'raining']
  ['Partly Cloudy' 'Sunny' 'Partly Cloudy']
  ['Sunny' 'Sunny' 'Partly Cloudy']]

 [['sunny' 'sunny' 'Partly sunny']
  ['Raining' 'Sunny' 'Partly Cloudy']
  ['Sunny' 'windy' 'Partly Cloudy']]]


# Basic Information
    ## Shape: rows and cols
    ## Size : number of elements
    ## Dimension : return 1,2,3...
    ## Data type : return stored data values type

In [37]:
print(array1)

[10 20 30 40 50]


In [38]:
print("Shape of array1 : ",array1.shape)

Shape of array1 :  (5,)


In [39]:
print("Size of array1: ",array1.size)

Size of array1:  5


In [40]:
print('Dimension : ', array1.ndim)

Dimension :  1


In [41]:
print('Data Type : ', array1.dtype)

Data Type :  int64


In [42]:
students=np.array(['Arif',' Gogu', 'KY', 'Chun Wei', 'Miza'])

In [43]:
print(students)

['Arif' ' Gogu' 'KY' 'Chun Wei' 'Miza']


In [44]:
print('Shape of Array :', students.shape)

Shape of Array : (5,)


In [45]:
print("Number of students: ",students.size)

Number of students:  5


In [46]:
print('Data Type : ', students.dtype)

Data Type :  <U8


# Mathematical Operation

In [47]:
print(array1)

[10 20 30 40 50]


In [49]:
total=np.sum(array1)

In [50]:
print(total)

150


In [52]:
print('Mean:',np.mean(array1))

Average: 30.0


In [53]:
print('Max:',np.max(array1))

Max: 50


In [55]:
print('Min:',np.min(array1))

Min: 10


In [56]:
print('Index of Min:',np.argmin(array1))

Index of Min: 0


In [57]:
print('Index of Max:',np.argmax(array1))

Index of Max: 4


In [58]:
our_arr=np.array([100,200,300,7000,800,500,300,1900,600])

In [59]:
print(our_arr)

[ 100  200  300 7000  800  500  300 1900  600]


# searching and sorting Example in 1-D array

In [64]:
sorted_arr=np.sort(our_arr)
print('*****Sorted Array*****')
print(sorted_arr)

*****Sorted Array*****
[ 100  200  300  300  500  600  800 1900 7000]


In [66]:
print('any Example: ',np.any(sorted_arr>500))

any Example:  True


In [67]:
print('All greater than 500?: ',np.all(sorted_arr>500))

All greater than 500:  False


In [70]:
print('All greater than 99?: ',np.all(sorted_arr>99))

All greater than 99?:  True


In [71]:
print('Where values >500: ',np.where(sorted_arr>500))

Where values >500:  (array([5, 6, 7, 8]),)


In [73]:
print('All Number greater than 500')
for num in np.where(sorted_arr>500):
    print(num)

All Number greater than 500
[5 6 7 8]


In [74]:
print('All Number greater than 500')
for num in sorted_arr>500:
    print(num)

All Number greater than 500
False
False
False
False
False
True
True
True
True


In [75]:
selected_values=sorted_arr[sorted_arr>500]
print(selected_values)

[ 600  800 1900 7000]


In [81]:
##or code this way
for num in selected_values:
    print(num)

600
800
1900
7000


In [82]:
## or code this way
for num in sorted_arr[sorted_arr>500]:
    print(num)

600
800
1900
7000


In [83]:
## or this way
print(' ',sorted_arr[sorted_arr>500])

  [ 600  800 1900 7000]


# Slicing 1-D Array
    1.To take elememts from the starting index to end index
    2.e.g. [start:end]

In [86]:
print (sorted_arr)

[ 100  200  300  300  500  600  800 1900 7000]


In [88]:
slice_our_arr=sorted_arr[1:3]
print(slice_our_arr)

[200 300]


# starting from index and going till last

In [89]:
print(sorted_arr[3:])

[ 300  500  600  800 1900 7000]


In [90]:
print(sorted_arr[:4])

[100 200 300 300]


In [91]:
print(sorted_arr[5:])

[ 600  800 1900 7000]


# step
    ## [start:end:step]
    ## step: every step element

In [92]:
our_slice=sorted_arr[1:6:2]
print(our_slice)

[200 300 600]


In [95]:
print('Original Array')
print(sorted_arr)
print('Every Third element')
every_third_element=sorted_arr[ : :3] # amik data selang 3 kli
print(every_third_element)

Original Array
[ 100  200  300  300  500  600  800 1900 7000]
Every Third element
[100 300 800]


# Slice Reverse

In [97]:
print('Original Array')
print(sorted_arr)
print('Reverse Array: ')
print(sorted_arr[::-1])

Original Array
[ 100  200  300  300  500  600  800 1900 7000]
Reverse Array: 
[7000 1900  800  600  500  300  300  200  100]


In [99]:
print('Last five element')
print(sorted_arr[-5:])

Last five element
[ 500  600  800 1900 7000]


In [100]:
print('Slicing Done')

Slicing Done
